### ISSUE TITLE
Turning motors broken

### ISSUE THREAD

**Issue by Ronin-the-Barbarian** [thucchi-cs/9428CashewChickens#4]
Turning motors do not know they are facing the opposite direction. Therefore, leading the driving motors to incorrectly invert / not be inverted. Why?

**Comment by Ronin-the-Barbarian** [comment]
Narrowed down to issue with `getCurrentAngleRad()`

**Comment by thucchi-cs** [comment]
Fixed `getCurrentAngleRad()`
